### ISSUE TITLE
Finish up filtering logic

### ISSUE THREAD

**Issue by ghost** [CodersCamp2021-HK/CodersCamp2021.Project.Fullstack#157]
- Na stronie Main żądać z backendu poprawny podzbiór dishy bazując na zaznaczonych filtrach.
- Uporządkować dania w zależności od zaznaczonego w lewym panelu porządku.
- Dodać filtr bazujący na cuisine type (blokowane przez #184)

**Comment by tchojnacki** [comment]
> Branch [issue-157-Connect_the_MainPage_with_ShoppingCart_through_the_ShoppingCartContext](https://github.com/CodersCamp2021-HK/CodersCamp2021.Project.Fullstack/tree/issue-157-Connect_the_MainPage_with_ShoppingCart_through_the_ShoppingCartContext) created!

Troszkę namieszałem, poprawny branch to: [issue-157-Finish_up_filtering_logic](https://github.com/CodersCamp2021-HK/CodersCamp2021.Project.Fullstack/tree/issue-157-Finish_up_filtering_logic).
