### ISSUE TITLE
Setup deployment server with CD

### ISSUE THREAD

**Issue by hkawalek** [CodersCamp2021-HK/CodersCamp2021.Project.Fullstack#2]
- [x] atlas https://docs.atlas.mongodb.com/getting-started/
- [x] heroku https://www.mongodb.com/developer/how-to/use-atlas-on-heroku/
- [ ] CD github actions

**Comment by tchojnacki** [comment]
Serwer i baza wiszą (a przynajmniej u mnie działa): https://coderscamp2021-hk-fullstack.herokuapp.com/api/

Zostało mi do ogarnięcia CD, ale to dopiero jutro.
